name = "jarvis"
main = "src/index.ts"
compatibility_date = "2026-10-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

# Spracherkennung (Whisper)
[ai]
binding = "AI"

# KV-Speicher
[[kv_namespaces]]
binding = "SPEICHER"
id = "46080b1ff0a64957b771b53c7543dcc6"
